In [1]:
import numpy as np
import pandas as pd
from typing import List
def Generator(rasio: int, panjangData: int, angkaTarget: int) -> List[float] :
    total = sum(rasio)
    probabilitas = np.array([x / total for x in rasio])

    num_samples = min(panjangData,len(rasio))

    while True:
        random_number = np.random.choice(range(1,len(rasio) +1 ), size=num_samples,p = probabilitas)
        while len(random_number) < panjangData:
            random_number = np.append(random_number, np.random.choice(range(1,len(rasio) +1 ), size=1,p = probabilitas))
        # print(random_number)
        if sum(random_number) == angkaTarget:
            break

    np.random.shuffle(random_number)
    return random_number

X1 = [35,35,40,38,42,40,38,44,40,40,41,43,49,45,35,40,41,38,40,38,37,37,38,41,40,38,40,39,45,42,45,49,36,39,41,45,42,47,40,38,42,38,39,35,42,36,37,34,31,34,40,41]
# dataGenerated = []
# Rasio = [1,1,15,47,36]
# for x in targetArray:
#     Result = Generator(Rasio,10,x)
#     dataGenerated.append(Result)
#     print(f"final: {Result}")
#     print(len(Result))
#     print(sum(Result))

# display(dataGenerated)

In [2]:
X1 = [35,35,40,38,42,40,38,44,40,40,41,43,49,45,35,40,41,38,40,38,37,37,38,41,40,38,40,39,45,42,45,49,36,39,41,45,42,47,40,38,42,38,39,35,42,36,37,34,31,34,40,41]
X2 = [33,37,39,35,42,45,37,45,46,45,38,42,48,46,38,38,45,38,43,38,44,40,37,40,38,43,35,37,43,40,37,49,40,41,36,40,44,40,43,41,40,38,39,37,40,35,41,44,34,42,43,39]
X3 = [35,36,39,37,38,48,35,42,38,39,40,44,49,43,37,39,42,42,40,40,41,38,40,39,40,45,40,40,48,40,41,50,46,40,40,41,40,43,41,40,42,38,44,39,40,45,50,30,34,32,42,43]
Y = [37,38,38,34,38,40,36,38,40,41,40,45,47,49,33,39,42,40,41,40,41,36,35,38,39,45,46,39,44,44,45,48,44,43,42,45,46,49,45,44,45,40,46,41,43,39,45,32,35,34,44,45]
X1Data = []
X2Data = []
X3Data = []
YData = []
Rasio = [1,1,15,47,36]
for x in X1:
    Result = Generator(Rasio,10,x)
    X1Data.append(Result)
for x in X2:
    Result = Generator(Rasio,10,x)
    X2Data.append(Result)
for x in X3:
    Result = Generator(Rasio,10,x)
    X3Data.append(Result)
for x in Y:
    Result = Generator(Rasio,10,x)
    YData.append(Result)

In [3]:
fulldata = [X1Data,X2Data,X3Data,YData]
display(fulldata)

[[array([4, 3, 3, 4, 3, 4, 3, 3, 3, 5]),
  array([5, 4, 3, 5, 1, 3, 3, 4, 4, 3]),
  array([4, 4, 4, 5, 4, 4, 1, 5, 4, 5]),
  array([4, 4, 4, 4, 4, 3, 4, 4, 3, 4]),
  array([5, 4, 5, 4, 4, 4, 3, 4, 4, 5]),
  array([3, 4, 5, 3, 4, 4, 4, 4, 5, 4]),
  array([4, 5, 3, 4, 3, 5, 3, 3, 4, 4]),
  array([4, 5, 5, 3, 5, 4, 4, 5, 4, 5]),
  array([3, 4, 4, 4, 4, 5, 4, 4, 5, 3]),
  array([5, 3, 4, 5, 4, 2, 5, 3, 5, 4]),
  array([5, 5, 3, 3, 4, 4, 4, 4, 4, 5]),
  array([5, 3, 4, 5, 3, 5, 4, 4, 5, 5]),
  array([5, 5, 5, 5, 4, 5, 5, 5, 5, 5]),
  array([5, 5, 3, 5, 5, 4, 4, 5, 4, 5]),
  array([5, 3, 4, 3, 3, 3, 4, 4, 1, 5]),
  array([4, 5, 4, 1, 4, 5, 4, 5, 4, 4]),
  array([5, 5, 4, 4, 4, 4, 4, 3, 4, 4]),
  array([3, 4, 3, 5, 4, 4, 4, 4, 4, 3]),
  array([4, 3, 5, 4, 4, 2, 4, 5, 4, 5]),
  array([4, 2, 5, 4, 4, 3, 4, 4, 4, 4]),
  array([5, 4, 5, 3, 3, 5, 3, 3, 1, 5]),
  array([3, 4, 4, 3, 4, 3, 4, 4, 4, 4]),
  array([2, 5, 4, 3, 4, 5, 4, 4, 3, 4]),
  array([5, 3, 5, 5, 5, 4, 1, 4, 5, 4]),
  array([4, 5, 5

In [4]:

x1_1_data =[row[0] for row in X1Data]
x1_2_data = [row[1] for row in X1Data]
x1_3_data = [row[2] for row in X1Data]
x1_4_data = [row[3] for row in X1Data]
x1_5_data = [row[4] for row in X1Data]
x1_6_data = [row[5] for row in X1Data]
x1_7_data = [row[6] for row in X1Data]
x1_8_data = [row[7] for row in X1Data]
x1_9_data = [row[8] for row in X1Data]
x1_10_data = [row[9] for row in X1Data]

x2_1_data = [row[0] for row in X2Data]
x2_2_data = [row[1] for row in X2Data]
x2_3_data = [row[2] for row in X2Data]
x2_4_data = [row[3] for row in X2Data]
x2_5_data = [row[4] for row in X2Data]
x2_6_data = [row[5] for row in X2Data]
x2_7_data = [row[6] for row in X2Data]
x2_8_data = [row[7] for row in X2Data]
x2_9_data = [row[8] for row in X2Data]
x2_10_data = [row[9] for row in X2Data]

x3_1_data = [row[0] for row in X3Data]
x3_2_data = [row[1] for row in X3Data]
x3_3_data = [row[2] for row in X3Data]
x3_4_data = [row[3] for row in X3Data]
x3_5_data = [row[4] for row in X3Data]
x3_6_data = [row[5] for row in X3Data]
x3_7_data = [row[6] for row in X3Data]
x3_8_data = [row[7] for row in X3Data]
x3_9_data = [row[8] for row in X3Data]
x3_10_data = [row[9] for row in X3Data]

x4_1_data = [row[0] for row in YData]
x4_2_data = [row[1] for row in YData]
x4_3_data = [row[2] for row in YData]
x4_4_data = [row[3] for row in YData]
x4_5_data = [row[4] for row in YData]
x4_6_data = [row[5] for row in YData]
x4_7_data = [row[6] for row in YData]
x4_8_data = [row[7] for row in YData]
x4_9_data = [row[8] for row in YData]
x4_10_data = [row[9] for row in YData]


x1_data = [x1_1_data,x1_2_data,x1_3_data,x1_4_data,x1_5_data,x1_6_data,x1_7_data,x1_8_data,x1_9_data,x1_10_data]
x2_data = [x2_1_data,x2_2_data,x2_3_data,x2_4_data,x2_5_data,x2_6_data,x2_7_data,x2_8_data,x2_9_data,x2_10_data]
x3_data = [x3_1_data,x3_2_data,x3_3_data,x3_4_data,x3_5_data,x3_6_data,x3_7_data,x3_8_data,x3_9_data,x3_10_data]
y1_data = [x4_1_data,x4_2_data,x4_3_data,x4_4_data,x4_5_data,x4_6_data,x4_7_data,x4_8_data,x4_9_data,x4_10_data]

# for x in range(52):
#     for y in X1Data[x]:
#         x1_2_data.append(y)



# x2_data = []
# x3_data = []
# y1_data = []

# display(x1_data)
# display(x2_data)
# display(x3_data)
# display(y1_data)

# # Creating a DataFrame
df = pd.DataFrame({
   'x1.1': x1_data[0], 'x1.2': x1_data[1], 'x1.3': x1_data[2], 'x1.4': x1_data[3], 'x1.5': x1_data[4],
    'x1.6': x1_data[5], 'x1.7': x1_data[6], 'x1.8': x1_data[7], 'x1.9': x1_data[8], 'x1.10': x1_data[9],
    'x2.1': x2_data[0], 'x2.2': x2_data[1], 'x2.3': x2_data[2], 'x2.4': x2_data[3], 'x2.5': x2_data[4],
    'x2.6': x2_data[5], 'x2.7': x2_data[6], 'x2.8': x2_data[7], 'x2.9': x2_data[8], 'x2.10': x2_data[9],
    'x3.1': x3_data[0], 'x3.2': x3_data[1], 'x3.3': x3_data[2], 'x3.4': x3_data[3], 'x3.5': x3_data[4],
    'x3.6': x3_data[5], 'x3.7': x3_data[6], 'x3.8': x3_data[7], 'x3.9': x3_data[8], 'x3.10': x3_data[9],
    'y.1': y1_data[0], 'y.2': y1_data[1], 'y.3': y1_data[2], 'y.4': y1_data[3], 'y.5': y1_data[4],
    'y.6': y1_data[5], 'y.7': y1_data[6], 'y.8': y1_data[7], 'y.9': y1_data[8], 'y.10': y1_data[9]
})
display(df)

x1.1  x1.2  x1.3  x1.4  x1.5  x1.6  x1.7  x1.8  x1.9  x1.10  ...  y.1  \
0      4     3     3     4     3     4     3     3     3      5  ...    3   
1      5     4     3     5     1     3     3     4     4      3  ...    3   
2      4     4     4     5     4     4     1     5     4      5  ...    4   
3      4     4     4     4     4     3     4     4     3      4  ...    3   
4      5     4     5     4     4     4     3     4     4      5  ...    3   
5      3     4     5     3     4     4     4     4     5      4  ...    3   
6      4     5     3     4     3     5     3     3     4      4  ...    2   
7      4     5     5     3     5     4     4     5     4      5  ...    4   
8      3     4     4     4     4     5     4     4     5      3  ...    4   
9      5     3     4     5     4     2     5     3     5      4  ...    4   
10     5     5     3     3     4     4     4     4     4      5  ...    4   
11     5     3     4     5     3     5     4     4     5      5  ...    4   
12     5     5     5     5     4     5     5     5     5      5  ...    5   
13     5     5     3     5     5     4     4     5     4      5  ...    5   
14     5     3     4     3     3     3     4     4     1      5  ...    3   
15     4     5     4     1     4     5     4     5     4      4  ...    4   
16     5     5     4     4     4     4     4     3     4      4  ...    4   
17     3     4     3     5     4     4     4     4     4      3  ...    4   
18     4     3     5     4     4     2     4     5     4      5  ...    4   
19     4     2     5     4     4     3     4     4     4      4  ...    5   
20     5     4     5     3     3     5     3     3     1      5  ...    4   
21     3     4     4     3     4     3     4     4     4      4  ...    4   
22     2     5     4     3     4     5     4     4     3      4  ...    3   
23     5     3     5     5     5     4     1     4     5      4  ...    4   
24     4     5     5     1     5     4     5     5     3      3  ...    3   
25     3     5     4     3     4     3     2     4     5      5  ...    4   
26     4     4     3     4     5     5     3     4     4      4  ...    5   
27     5     4     4     4     5     3     3     4     4      3  ...    4   
28     5     4     5     4     4     5     4     5     4      5  ...    4   
29     4     5     1     4     5     5     4     5     4      5  ...    3   
30     5     4     4     5     5     4     5     5     3      5  ...    4   
31     5     5     5     5     5     5     5     4     5      5  ...    5   
32     1     5     3     1     4     5     5     5     4      3  ...    4   
33     3     5     3     4     4     4     3     4     5      4  ...    4   
34     4     5     3     5     4     4     4     3     4      5  ...    4   
35     5     5     4     4     5     4     4     5     5      4  ...    5   
36     4     5     5     4     4     4     4     3     4      5  ...    4   
37     5     5     4     5     4     5     5     4     5      5  ...    5   
38     5     4     3     4     4     4     5     3     4      4  ...    4   
39     5     2     5     5     4     4     5     2     2      4  ...    4   
40     4     4     4     4     5     4     4     4     4      5  ...    5   
41     5     1     4     3     5     4     5     4     3      4  ...    4   
42     5     3     4     5     3     4     3     3     5      4  ...    5   
43     3     3     4     4     3     3     4     4     3      4  ...    4   
44     5     3     4     3     5     4     4     5     5      4  ...    4   
45     3     1     4     4     5     4     4     4     4      3  ...    3   
46     4     3     4     2     4     4     4     4     4      4  ...    4   
47     1     3     3     3     4     4     3     5     4      4  ...    4   
48     3     3     5     3     4     4     1     4     1      3  ...    4   
49     1     3     4     3     3     5     3     4     4      4  ...    4   
50     4     5     5     4     5     3     2     3     4      5  ...    5   


In [5]:
# df.to_excel('GeneratorNumber.xlsx', index=False)

In [6]:
datadim = np.array(fulldata)
print(datadim.shape)

(4, 52, 10)


In [7]:

# Menggabungkan semua data menjadi satu dimensi
flat_data = np.concatenate(datadim[3])

# Menghitung frekuensi masing-masing angka
counts = np.bincount(flat_data)


# Menghitung total elemen dalam data
total_elements = len(flat_data)

# Menghitung presentase masing-masing angka
percentages = (counts[1:] / total_elements) * 100

# Menampilkan hasil
for i, percentage in enumerate(percentages, start=1):
    print(f"Presentase angka {i}: {percentage:.2f}%")


Presentase angka 1: 2.50%
Presentase angka 2: 0.58%
Presentase angka 3: 15.96%
Presentase angka 4: 44.23%
Presentase angka 5: 36.73%
