In [5]:
import numpy as np
import pandas as pd
from typing import List
def Generator(rasio: int, panjangData: int, angkaTarget: int) -> List[float] :
    total = sum(rasio)
    probabilitas = np.array([x / total for x in rasio])

    num_samples = min(panjangData,len(rasio))

    while True:
        random_number = np.random.choice(range(1,len(rasio) +1 ), size=num_samples,p = probabilitas)
        while len(random_number) < panjangData:
            random_number = np.append(random_number, np.random.choice(range(1,len(rasio) +1 ), size=1,p = probabilitas))
        # print(random_number)
        if sum(random_number) == angkaTarget:
            break

    np.random.shuffle(random_number)
    return random_number

X1 = [35,35,40,38,42,40,38,44,40,40,41,43,49,45,35,40,41,38,40,38,37,37,38,41,40,38,40,39,45,42,45,49,36,39,41,45,42,47,40,38,42,38,39,35,42,36,37,34,31,34,40,41]
dataGenerated = []
Rasio = [1,1,15,47,36]
for x in X1:
    Result = Generator(Rasio,10,x)
    dataGenerated.append(Result)
    print(f"final: {Result}")
    print(len(Result))
    print(sum(Result))

display(dataGenerated)

final: [4 3 3 4 3 1 5 3 4 5]
10
35
final: [4 3 4 1 3 4 5 4 4 3]
10
35
final: [4 4 5 5 4 3 4 4 3 4]
10
40
final: [4 1 4 4 5 3 4 5 5 3]
10
38
final: [4 5 4 4 3 4 5 4 4 5]
10
42
final: [3 5 5 5 5 4 3 3 4 3]
10
40
final: [5 4 4 4 2 5 3 5 3 3]
10
38
final: [5 4 5 4 5 4 4 4 5 4]
10
44
final: [4 4 4 4 4 5 3 4 4 4]
10
40
final: [4 4 3 4 5 3 5 4 4 4]
10
40
final: [4 4 4 4 5 3 5 4 4 4]
10
41
final: [4 4 4 5 5 4 5 4 4 4]
10
43
final: [5 5 5 5 5 5 4 5 5 5]
10
49
final: [5 4 5 5 3 5 5 3 5 5]
10
45
final: [5 5 4 4 3 1 4 3 2 4]
10
35
final: [3 3 5 3 4 4 5 5 4 4]
10
40
final: [4 4 4 4 5 3 5 4 4 4]
10
41
final: [5 4 3 3 3 4 3 4 4 5]
10
38
final: [5 4 4 4 3 4 4 4 5 3]
10
40
final: [4 4 3 4 4 5 5 4 4 1]
10
38
final: [4 5 3 4 3 1 4 4 5 4]
10
37
final: [3 4 4 4 4 3 3 5 3 4]
10
37
final: [5 5 4 4 4 3 3 2 3 5]
10
38
final: [4 4 4 4 5 4 3 4 5 4]
10
41
final: [4 5 4 4 3 4 4 4 4 4]
10
40
final: [3 4 2 4 4 4 4 4 5 4]
10
38
final: [3 4 3 5 5 4 4 4 4 4]
10
40
final: [3 4 4 5 3 5 4 3 3 5]
10
39
final: [5 5 5 4 3 4 

[array([4, 3, 3, 4, 3, 1, 5, 3, 4, 5]),
 array([4, 3, 4, 1, 3, 4, 5, 4, 4, 3]),
 array([4, 4, 5, 5, 4, 3, 4, 4, 3, 4]),
 array([4, 1, 4, 4, 5, 3, 4, 5, 5, 3]),
 array([4, 5, 4, 4, 3, 4, 5, 4, 4, 5]),
 array([3, 5, 5, 5, 5, 4, 3, 3, 4, 3]),
 array([5, 4, 4, 4, 2, 5, 3, 5, 3, 3]),
 array([5, 4, 5, 4, 5, 4, 4, 4, 5, 4]),
 array([4, 4, 4, 4, 4, 5, 3, 4, 4, 4]),
 array([4, 4, 3, 4, 5, 3, 5, 4, 4, 4]),
 array([4, 4, 4, 4, 5, 3, 5, 4, 4, 4]),
 array([4, 4, 4, 5, 5, 4, 5, 4, 4, 4]),
 array([5, 5, 5, 5, 5, 5, 4, 5, 5, 5]),
 array([5, 4, 5, 5, 3, 5, 5, 3, 5, 5]),
 array([5, 5, 4, 4, 3, 1, 4, 3, 2, 4]),
 array([3, 3, 5, 3, 4, 4, 5, 5, 4, 4]),
 array([4, 4, 4, 4, 5, 3, 5, 4, 4, 4]),
 array([5, 4, 3, 3, 3, 4, 3, 4, 4, 5]),
 array([5, 4, 4, 4, 3, 4, 4, 4, 5, 3]),
 array([4, 4, 3, 4, 4, 5, 5, 4, 4, 1]),
 array([4, 5, 3, 4, 3, 1, 4, 4, 5, 4]),
 array([3, 4, 4, 4, 4, 3, 3, 5, 3, 4]),
 array([5, 5, 4, 4, 4, 3, 3, 2, 3, 5]),
 array([4, 4, 4, 4, 5, 4, 3, 4, 5, 4]),
 array([4, 5, 4, 4, 3, 4, 4, 4, 4, 4]),


In [15]:
import numpy as np
from collections import Counter

def Generator(ratio, data_length, target_sum):
    total = sum(ratio)
    probabilities = np.array([x / total for x in ratio])

    num_samples = min(data_length, len(ratio))

    while True:
        random_numbers = np.random.choice(range(1, len(ratio) + 1), size=num_samples, p=probabilities)
        while len(random_numbers) < data_length:
            random_numbers = np.append(random_numbers, np.random.choice(range(1, len(ratio) + 1), size=1, p=probabilities))

        if sum(random_numbers) == target_sum:
            break

    np.random.shuffle(random_numbers)
    return random_numbers

def hitung_jumlah_dan_persentase(data):
    counts = Counter(data)
    total_data = len(data)
    percentages = {key: (count / total_data) * 100 for key, count in counts.items()}
    return counts, percentages

def cek_persentase(data, persentase_tentukan):
    _, percentages = hitung_jumlah_dan_persentase(data)
    
    for angka, persentase in percentages.items():
        if persentase != persentase_tentukan[angka]:
            return False
    
    return True

ratio = [7, 7, 10, 32, 44]
target_validation = np.array([
    35, 35, 40, 38, 42, 40, 38, 44, 40, 40, 41, 43, 49, 45, 35, 40, 41, 38, 40, 38, 37, 37, 38, 41, 40, 38, 40, 39, 45, 42, 45, 49, 36, 39, 41, 45, 42, 47, 40, 38, 42, 38, 39, 35, 42, 36, 37, 34, 31, 34, 40, 41
])

# Persentase angka
persentase_tentukan = {1: 7, 2: 7, 3: 10, 4: 32, 5: 44}

# Generate data until percentages match
max_attempts = 5000
for attempt in range(max_attempts):
    X1_data = [Generator(ratio, 10, i) for i in target_validation]
    All_X1 = np.array(X1_data).T #Transpose matriks

    percentages_match = all(cek_persentase(column_data, persentase_tentukan) for column_data in All_X1.T)
    
    if percentages_match:
        print(f"Success! Data generated in {attempt + 1} attempts.")
        break

if not percentages_match:
    print(f"Failed to generate data with matching percentages after {max_attempts} attempts.")


Failed to generate data with matching percentages after 5000 attempts.
