In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])
b = np.array([1.5,2.5,5.6,7])
print(a)

[1 2 3 4]


In [9]:
c = np.zeros([5,5])
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [10]:
d = np.ones([4,4])
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
