In [142]:
import numpy as np
import math
import random

In [103]:
a = np.array(['a','b','c','d'])
print(a)
print(np.__version__)

b = np.array(['8','2','3','5','5'],dtype = 'i')
c = np.array([b],ndmin = 3)
print(c)
b = b[4] + 2
print(b)
for x in c:
    for z in c:
        print(x+z)
z = 2
numb = np.array([z+np.random.randn() for i in range(50)])
print(numb[:12])
num = np.linspace(1,50)
print(num[:14])
numb =numb.astype(int)
print(numb[::2])
dim0 = np.linspace(2,20,10)
dim1 = np.linspace(3,30,10)
dim2 = np.linspace(4,40,10)
dim2_array = np.array([dim0,dim1,dim2])
print(dim2_array[:,5])
print(dim3_array)
print(numb)
print(numb[::2])
print(len(numb))

['a' 'b' 'c' 'd']
1.21.5
[[[8 2 3 5 5]]]
7
[[16  4  6 10 10]]
[2.72202133 2.92391591 3.79839685 2.71985938 1.83811299 1.08282464
 1.77749716 2.483606   1.74497004 2.56894137 2.3170287  2.16287703]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.]
[2 3 1 1 1 2 2 0 1 2 0 2 3 2 0 1 0 0 2 2 3 1 3 2 4]
[12. 18. 24.]
[[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
 [ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30.]
 [ 4.  8. 12. 16. 20. 24. 28. 32. 36. 40.]]
[2 2 3 2 1 1 1 2 1 2 2 2 2 1 0 1 1 1 2 3 0 3 2 0 3 1 2 1 0 1 1 1 0 1 0 1 2
 0 2 0 3 3 1 2 3 2 2 2 4 0]
[2 3 1 1 1 2 2 0 1 2 0 2 3 2 0 1 0 0 2 2 3 1 3 2 4]
50


In [106]:
a = numb.view()
a[0]= 11
print(a)

[11  2  3  2  1  1  1  2  1  2  2  2  2  1  0  1  1  1  2  3  0  3  2  0
  3  1  2  1  0  1  1  1  0  1  0  1  2  0  2  0  3  3  1  2  3  2  2  2
  4  0]


In [151]:
print(np.ndim(dim2_array))
print(dim2_array.shape)

arra = np.array([a+1 for a in range(4)])
print(np.ndim(arra))
print(arra)
a = lambda x:math.sqrt(x)
print(a(4))
print(np.sum(arra))
lam = lambda lam:lam *np.sum(arra)
print(lam(2))

iff = lambda a: "yes" if a < 2 else "no"
print(iff(0))

rando = np.array([random.randint(1,20) for i in range(20)])
print(rando)

2
(3, 10)
1
[1 2 3 4]
2.0
10
20
yes
[12 12 11  1  3 20  2 13  6 17 18 15 19 14  1 17 15 13 11  8]


In [156]:
print(np.sort(rando))
x = 0
for a in rando:
    if a == 15:
        x = x+1
    else:
        continue
print(x)

[ 1  1  2  3  6  8 11 11 12 12 13 13 14 15 15 17 17 18 19 20]
2


In [165]:
a = random.randint(1,3)
x = np.array([a+random.random() for i in range(20)])
print(x)
print(np.sort(x))

[3.56187672 3.67829074 3.48024041 3.0642788  3.29568831 3.22170284
 3.37138239 3.53841721 3.20906719 3.11344183 3.83599215 3.99610044
 3.67302487 3.9272832  3.77419704 3.40124694 3.47163667 3.84610611
 3.74816941 3.71273881]
[3.0642788  3.11344183 3.20906719 3.22170284 3.29568831 3.37138239
 3.40124694 3.47163667 3.48024041 3.53841721 3.56187672 3.67302487
 3.67829074 3.71273881 3.74816941 3.77419704 3.83599215 3.84610611
 3.9272832  3.99610044]


In [173]:
arr1 = np.array([random.randint(1,20) for i in range(20)])
print(arr1)
arr1_new = arr1.reshape(4,5)
print(arr1_new)
print(np.shape(arr1_new))

[17  6  1 20 11  6  3  9  6 12 15  1 17 15  5 20  4  7 15 10]
[[17  6  1 20 11]
 [ 6  3  9  6 12]
 [15  1 17 15  5]
 [20  4  7 15 10]]
(4, 5)


In [194]:
arr2 = np.arange(27)
arr2_new = arr2.reshape(3,3,3)
print(arr2)
print(arr2_new)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [195]:
arr3 = np.arange(0,50,2)
arr3_new = arr3.reshape(5,5)
print(arr3_new)

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]


In [199]:
arr4 = np.arange(8)
arr4_new = arr4.reshape(2,2,-1)
print(arr4_new)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [216]:
a = np.arange(0,20,3)
print(a)
b = np.arange(0,40,6)
arr5 = np.array([a,b])
arr5_new = arr5.reshape(-3)
print(arr5_new)
a = a[np.newaxis,:]
print(a.shape,a.ndim)


[ 0  3  6  9 12 15 18]
[ 0  3  6  9 12 15 18  0  6 12 18 24 30 36]
(1, 7) 2


In [229]:
arr6 = np.arange(20,100,2)
# for x in arr6:
#     print(x)
print(len(arr6))
arr6_new = arr6.reshape(5,8)
print(arr6_new)
for x in arr6_new:
    for i in x:
        print(i)

40
[[20 22 24 26 28 30 32 34]
 [36 38 40 42 44 46 48 50]
 [52 54 56 58 60 62 64 66]
 [68 70 72 74 76 78 80 82]
 [84 86 88 90 92 94 96 98]]
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99
